# Generated by Django 5.1.2 on 2024-10-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prep_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='cv',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='CV',
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
