# Generated by Django 5.1.2 on 2024-10-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep_app', '0004_alter_workexperience_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='honours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
