# Generated by Django 5.1.2 on 2024-10-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep_app', '0006_topic_question_usersubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='initial_code',
            field=models.JSONField(help_text='Initial code template for each language'),
        ),
        migrations.AlterField(
            model_name='question',
            name='solution',
            field=models.JSONField(help_text='Solution code for each language'),
        ),
    ]
