# Generated by Django 5.1.2 on 2024-10-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep_app', '0008_usercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='solution',
            field=models.JSONField(blank=True, help_text='Solution code for each language', null=True),
        ),
    ]
