# Generated by Django 5.1.2 on 2025-09-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prep_app', '0009_alter_question_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='workexperiencedescription',
            name='work_experience',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
        migrations.DeleteModel(
            name='WorkExperienceDescription',
        ),
    ]
