# Generated by Django 5.1.2 on 2026-07-19 15:25

import django.db.models.deletion
import hashlib
import re
from django.conf import settings
from django.db import migrations, models


def backfill_memory_contract(apps, schema_editor):
    CareerMemoryFact = apps.get_model('prep_app', 'CareerMemoryFact')
    seen = set()
    for fact in CareerMemoryFact.objects.order_by('user_id', 'id').iterator():
        normalized = '|'.join(
            re.sub(r'\s+', ' ', value).strip().casefold()
            for value in (fact.category, fact.title, fact.content)
        )
        fingerprint = hashlib.sha256(normalized.encode('utf-8')).hexdigest()
        key = (fact.user_id, fingerprint)
        if key in seen:
            fingerprint = hashlib.sha256(f'{normalized}|{fact.id}'.encode('utf-8')).hexdigest()
        seen.add((fact.user_id, fingerprint))
        fact.fingerprint = fingerprint
        fact.review_status = 'confirmed' if fact.user_confirmed else 'pending'
        if fact.source_session_id:
            fact.source_type = 'interview'
            fact.source_label = 'Imported from an existing interview session'
        else:
            fact.source_type = 'manual'
            fact.source_label = 'Existing Career Memory'
        fact.save(update_fields=['fingerprint', 'review_status', 'source_type', 'source_label'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('prep_app', '0011_career_memory_interview_coach'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadinessSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readiness_label', models.CharField(choices=[('insufficient_evidence', 'Not enough evidence yet'), ('building', 'Building towards the role'), ('mostly_ready', 'Mostly ready'), ('ready', 'Ready to interview')], max_length=30)),
                ('dimension_scores', models.JSONField(blank=True, default=dict)),
                ('target_role_gaps', models.JSONField(blank=True, default=list)),
                ('evidence_answer_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('target_role', models.CharField(blank=True, max_length=200)),
                ('job_description', models.TextField(blank=True)),
                ('document', models.JSONField(default=dict)),
                ('coverage_percent', models.PositiveSmallIntegerField(default=0)),
                ('source_memory_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='careermemoryfact',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='careermemoryfact',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='careermemoryfact',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Needs review'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='careermemoryfact',
            name='source_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='careermemoryfact',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Added by user'), ('cv', 'CV import'), ('interview', 'Interview answer')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='careermemoryfact',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='category',
            field=models.CharField(choices=[('behavioural', 'Behavioural'), ('technical', 'Technical discussion'), ('coding', 'Coding discussion'), ('system_design', 'System design'), ('graduate', 'Graduate'), ('leadership', 'Leadership'), ('product', 'Product'), ('data', 'Data'), ('mixed', 'Mixed / adaptive')], default='mixed', max_length=30),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='current_section',
            field=models.CharField(default='introduction', max_length=40),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='current_section_index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('cantonese', 'Cantonese'), ('bilingual', 'English + Cantonese'), ('english_cantonese_feedback', 'English interview + Cantonese feedback')], default='english', max_length=40),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='plan_sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='interviewturn',
            name='section',
            field=models.CharField(default='introduction', max_length=40),
        ),
        migrations.AlterField(
            model_name='careermemoryfact',
            name='category',
            field=models.CharField(choices=[('personal', 'Personal detail'), ('skill', 'Skill'), ('work_experience', 'Work experience'), ('project', 'Project'), ('education', 'Education'), ('achievement', 'Achievement'), ('certification', 'Certification'), ('language', 'Language'), ('experience', 'Other experience'), ('strength', 'Strength'), ('growth', 'Growth area'), ('preference', 'Preference'), ('goal', 'Goal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='careerprofile',
            name='preferred_language',
            field=models.CharField(choices=[('english', 'English'), ('cantonese', 'Cantonese'), ('bilingual', 'English + Cantonese'), ('english_cantonese_feedback', 'English interview + Cantonese feedback')], default='english', max_length=40),
        ),
        migrations.CreateModel(
            name='CandidateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('mime_type', models.CharField(max_length=120)),
                ('size_bytes', models.PositiveIntegerField()),
                ('content_sha256', models.CharField(max_length=64)),
                ('extracted_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='careermemoryfact',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_facts', to='prep_app.candidatedocument'),
        ),
        migrations.RunPython(backfill_memory_contract, noop_reverse),
        migrations.AddConstraint(
            model_name='careermemoryfact',
            constraint=models.UniqueConstraint(condition=models.Q(('fingerprint', ''), _negated=True), fields=('user', 'fingerprint'), name='unique_memory_fingerprint_per_user'),
        ),
        migrations.AddField(
            model_name='readinesssnapshot',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_snapshot', to='prep_app.interviewsession'),
        ),
        migrations.AddField(
            model_name='readinesssnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='candidatedocument',
            constraint=models.UniqueConstraint(fields=('user', 'content_sha256'), name='unique_candidate_document_per_user'),
        ),
    ]
