# Generated by Django 6.0.7 on 2026-07-24 20:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep_app', '0012_readinesssnapshot_resumeversion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=64)),
                ('identifier', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='careermemoryfact',
            index=models.Index(fields=['user', 'user_confirmed', 'review_status'], name='memory_confirmed_idx'),
        ),
        migrations.AddIndex(
            model_name='ratelimitevent',
            index=models.Index(fields=['scope', 'identifier', 'created_at'], name='ratelimit_lookup_idx'),
        ),
    ]
