"""
Django settings for interview_prep project.

Generated by 'django-admin startproject' using Django 4.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
from django.core.exceptions import ImproperlyConfigured
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# Vercel sets VERCEL=1 in every build and function invocation.
ON_VERCEL = bool(os.environ.get('VERCEL'))

# SECURITY WARNING: don't run with debug turned on in production!
# The default is False so that a forgotten environment variable fails closed
# rather than exposing tracebacks and secrets on a deployed host.
DEBUG = config('DEBUG', default=False, cast=bool)

# A local-only default keeps first-run setup approachable. Production refuses it.
_DEVELOPMENT_SECRET = 'aceinterview-local-development-key-change-before-deploying'
SECRET_KEY = config('DJANGO_SECRET_KEY', default=_DEVELOPMENT_SECRET)
if not DEBUG and SECRET_KEY == _DEVELOPMENT_SECRET:
    raise ImproperlyConfigured('DJANGO_SECRET_KEY must be set when DEBUG=False')

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',')])
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS', default='',
    cast=lambda v: [s.strip() for s in v.split(',') if s.strip()],
)

if ON_VERCEL:
    # Preview deployments get a generated *.vercel.app hostname per commit, so
    # the exact host is not knowable ahead of time.
    ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS + ['.vercel.app']))
    CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(
        CSRF_TRUSTED_ORIGINS + ['https://*.vercel.app']
    ))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'prep_app',
    'social_django',
    'codemirror',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'prep_app.middleware.ContentSecurityPolicyMiddleware',
]

# Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=not DEBUG, cast=bool)
# Only trust the forwarded-proto header where a proxy we control actually sets
# it. Vercel's edge overwrites it before the request reaches the function; on
# any other host a client could forge it and defeat the HTTPS redirect.
if ON_VERCEL:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
# Every front-end asset is committed under static/, so scripts and styles are
# restricted to this origin. Leave blank to use the policy defined in
# prep_app.middleware; set it to override the whole header.
CONTENT_SECURITY_POLICY = config('CONTENT_SECURITY_POLICY', default='')

# Session Security
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True

ROOT_URLCONF = 'interview_prep.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'interview_prep.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# SQLite is local-development only. A serverless deployment has a read-only
# filesystem and no instance affinity, so production must use DATABASE_URL.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
if config('DATABASE_URL', default=''):
    DATABASES['default'] = dj_database_url.config(
        conn_max_age=config('DB_CONN_MAX_AGE', default=600, cast=int),
        conn_health_checks=True,
        ssl_require=True,
    )
    # Managed Postgres is reached through a transaction-mode connection pooler,
    # which cannot hold the named cursors Django would otherwise open.
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True
elif ON_VERCEL:
    raise ImproperlyConfigured(
        'DATABASE_URL must be set on Vercel; the SQLite fallback is ephemeral.'
    )


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = config('STATIC_ROOT', default=os.path.join(BASE_DIR, 'staticfiles'))
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
GEMINI_API_KEY = config('GEMINI_API_KEY', default='')
INTERVIEW_COACH_USE_AI = config('INTERVIEW_COACH_USE_AI', default=True, cast=bool)
CAREER_MEMORY_USE_AI = config('CAREER_MEMORY_USE_AI', default=True, cast=bool)
INTERVIEW_COACH_MODEL = config('INTERVIEW_COACH_MODEL', default='gemini-2.5-flash-lite')
# Per-call deadline for Gemini. Keep it comfortably below the deployment's
# function duration limit (Vercel: 120s) so a slow model degrades to the
# deterministic fallback instead of timing out the whole request.
AI_REQUEST_TIMEOUT_SECONDS = config('AI_REQUEST_TIMEOUT_SECONDS', default=20, cast=int)

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = config('GOOGLE_OAUTH_CLIENT_ID', default='')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = config('GOOGLE_OAUTH_CLIENT_SECRET', default='')

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = 'home'  
SOCIAL_AUTH_LOGIN_ERROR_URL = 'register'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('HOST_EMAIL', default='')
EMAIL_HOST_PASSWORD = config('HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER or 'noreply@localhost')
PASSWORD_RESET_TIMEOUT = 60 * 60
# Socket timeout for the SMTP send, which happens inside the request. Django
# defaults this to None, i.e. block indefinitely, which on a serverless
# function means running to the platform's duration limit.
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=10, cast=int)

DATA_UPLOAD_MAX_MEMORY_SIZE = 11 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 11 * 1024 * 1024
